# Generated by Django 4.2.8 on 2024-01-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
